### ISSUE TITLE
No windows binaries available for Python 3.9

### ISSUE THREAD

**Issue by alphanoob1337** [PyMySQL/mysqlclient#452]
I realize that you don't offer support for Windows according to your documentation.

However, someone obviously provided Windows binary wheels for mysqlclient 2.0.1 for many Python versions. Can you please ask that person to also supply binaries for Python 3.9?

**Comment by SuperVirus** [comment]
Hi, I forked this repo as I needed Python 3.9 binaries, as well...
There is already a small pull request, but in the meantime you can find prebuild wheels in the [releases section of my fork](https://github.com/SuperVirus/mysqlclient-python/releases).

If you do not want to trust those binaries, you can fork my repository and run the GitHub Action "Build windows wheels" to build them yourself.

**Comment by methane** [comment]
I can not fix "_mysql.obj : error LNK2001: unresolved external symbol __imp_strncat" error.
https://github.com/PyMySQL/mysqlclient-python/runs/1497385830?check_suite_focus=true

So I can not release new wheel.

**Comment by SuperVirus** [comment]
That is strange, as I had no issues:
https://github.com/SuperVirus/mysqlclient-python/runs/1492467336?check_suite_focus=true

**Comment by methane** [comment]
MariaDB Connector/C was not built in your link.

**Comment by SuperVirus** [comment]
> 
> 
> MariaDB Connector/C was not built in your link.

You are right - it was the cached build done earlier...
Bbut it seems the GitHub cache action never worked as intended:
It used 'mariadb-connector-${CONNECTOR_VERSION}-win' as literal cache key and not 'mariadb-connector-3.1.11-win' as intended. Therefore it was never build with 3.1.11 but with 3.1.9 which I used before.

Please expect a new pull request fixing both issues shortly.

**Comment by SuperVirus** [comment]
Created pull request #455 to fix this issue.

**Comment by methane** [comment]
I released 2.0.2 with Python 3.9 on Windows wheels.
